# Clase 3- Media, desviación estándar y cuantiles

Trabajamos con la base de datos

https://www.kaggle.com/datasets/rkiattisak/student-performance-in-mathematics

In [3]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "exams.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "rkiattisak/student-performance-in-mathematics",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_2175/3051306654.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'student-performance-in-mathematics' dataset.
First 5 records:    gender race/ethnicity parental level of education         lunch  \
0  female        group D                some college      standard
1    male        group D          associate's degree      standard
2  female        group D                some college  free/reduced
3    male        group B                some college  free/reduced
4  female        group D          associate's degree      standard

  test preparation course  math score  reading score  writing score
0               completed          59             70             78
1                    none          96             93             87
2                    none          57             76             77
3                    none          70             70             63
4                    none          83             85             86

In [10]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group D,some college,standard,completed,59,70,78
1,male,group D,associate's degree,standard,none,96,93,87
2,female,group D,some college,free/reduced,none,57,76,77
3,male,group B,some college,free/reduced,none,70,70,63
4,female,group D,associate's degree,standard,none,83,85,86
...,...,...,...,...,...,...,...,...
995,male,group C,some college,standard,none,77,77,71
996,male,group C,some college,standard,none,80,66,66
997,female,group A,high school,standard,completed,67,86,86
998,male,group E,high school,standard,none,80,72,62
999,male,group D,high school,standard,none,58,47,45

In [35]:
## Filtramos la base de datos para el nivel de educación some college

df_some_college = df[df['parental level of education'] == 'some college']

In [36]:
df_some_college

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group D,some college,standard,completed,59,70,78
2,female,group D,some college,free/reduced,none,57,76,77
3,male,group B,some college,free/reduced,none,70,70,63
13,male,group A,some college,standard,none,70,73,70
16,female,group C,some college,free/reduced,none,35,47,41
...,...,...,...,...,...,...,...,...
962,female,group C,some college,standard,completed,59,66,71
964,female,group C,some college,free/reduced,none,62,74,74
972,female,group C,some college,standard,completed,80,88,90
995,male,group C,some college,standard,none,77,77,71
996,male,group C,some college,standard,none,80,66,66

In [17]:
df['parental level of education'].value_counts()

parental level of education
some college          224
high school           215
associate's degree    204
some high school      177
bachelor's degree     105
master's degree        75
Name: count, dtype: int64

In [34]:
## Filtramos la base de datos para el nivel de educación master degree


df_master_degree = df[df['parental level of education'] ==  "master's degree"]

In [29]:
df_master_degree

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
11,male,group B,master's degree,standard,none,53,50,49
14,male,group C,master's degree,free/reduced,none,55,54,52
15,male,group E,master's degree,free/reduced,none,56,46,43
33,female,group D,master's degree,free/reduced,none,32,35,37
39,male,group E,master's degree,standard,none,89,85,78
...,...,...,...,...,...,...,...,...
913,female,group D,master's degree,standard,none,69,67,78
920,male,group E,master's degree,standard,none,91,82,74
965,male,group C,master's degree,free/reduced,none,45,53,45
986,male,group D,master's degree,standard,none,88,72,78
987,female,group D,master's degree,standard,completed,87,95,100

In [21]:
import numpy as np

In [38]:
mean_level_some_college = np.mean(df_some_college['reading score'])
mean_level_master_degree = np.mean(df_master_degree['reading score'])

In [39]:
print(mean_level_some_college,mean_level_master_degree  )

70.94196428571429 71.97333333333333

In [40]:
# Calculemos las desviaciones estandar

#df_master_degree

#df_some_college

desv_some_college = np.std(df_some_college['reading score'])
desv_master_degree = np.std(df_master_degree['reading score'])

print(desv_some_college, desv_master_degree)

13.905010263473235 13.59801292673145

In [44]:
# Quantiles

# Quantiles para la variable reading score y nivel de educación correspondiente a some college

quantiles_some_college = np.quantile(df_some_college['reading score'], [0, 0.25, 0.5, 0.75, 1])
print(quantiles_some_college )

# Quantiles para la variable reading score y nivel de educación correspondiente a master degree

quantiles_master_degree = np.quantile(df_master_degree['reading score'], [0, 0.25, 0.5, 0.75, 1])
print(quantiles_master_degree )

[ 38.    61.    72.    80.25 100.  ]
[35.  64.5 72.  82.  98. ]